### ISSUE TITLE
Doesn't work if pip install aiida-lsmo (without -e optioin)

### ISSUE THREAD

**Issue by yakutovicha** [lsmo-epfl/aiida-lsmo#31]
When I run `Isotherm` workflow I get the problem:
```
...
  File "/home/aiida/.local/lib/python3.7/site-packages/aiida_lsmo/workchains/isotherm.py", line 55, in get_molecule_dict
    with open(yamlfile, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/aiida/.local/lib/python3.7/site-packages/aiida_lsmo/workchains/isotherm_data/isotherm_molecules.yaml'
```

One should add those files to `MANIFEST.in` so that they get included into the python package.

**Comment by danieleongari** [comment]
This problem then should be also extended to YAMLs containing the protocol of Multistage wc.
Thanks for reporting, I will make the MANIFEST.in
